envName = "release"
_envName = "dev"

[dev]
installDir = "${HOME}/.easifem/dev/install/"
buildDir = "${HOME}/.easifem/dev/build/"
sourceDir = "${HOME}/.easifem/src/"
lintDir = "${HOME}/.easifem/lint/"
buildType = "Debug"                          # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
buildSystem = "cmake"

[release]
buildDir = "${HOME}/.easifem/build/"
installDir = "${HOME}/.easifem/install/"
sourceDir = "${HOME}/.easifem/src/"
lintDir = "${HOME}/.easifem/lint/"
buildType = "Release"                    # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
buildSystem = "cmake"

[old]
buildDir = "${HOME}/.easifem/old/build/"
installDir = "${HOME}/.easifem/old/install/"
sourceDir = "${HOME}/.easifem/src/"
lintDir = "${HOME}/.easifem/old/lint/"
buildType = "Release"                        # "Debug", "Both"
buildSharedLibs = true
buildStaticLibs = true
buildSystem = "cmake"
