set -gx LD_LIBRARY_PATH /tmp/easifem/install/arpack/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/base/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/fftw/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/sparsekit/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/superlu/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/classes/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/lapack95/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/lis/lib $LD_LIBRARY_PATH
set -gx LD_LIBRARY_PATH /tmp/easifem/install/tomlf/lib $LD_LIBRARY_PATH
